### ISSUE TITLE
typescript compiler error TS2315: Type 'Middleware' is not generic.

### ISSUE THREAD

**Issue by powpi2000** [dlau/koa-body#134] opened 2019-02-26 16:32 UTC
## Problem/Feature Request Summary

koa-body run in npx(dev) ok, but compiler failure
## Environment Information

  * koa-body: 4.0.8
  * Koa: 2.6.2
  * Node.js: v11.6.0
  * tsc: 3.2.2

1. run tsc: (result: node_modules/koa-body/index.d.ts:155:63 - error TS2315: Type 'Middleware' is not generic.)

any on use koa-body in typescript compiler ok?

**Comment by MarkHerhold** [comment] 2019-02-26 18:09
Can you please provide a sample project to reproduce this issue?

**Comment by MarkHerhold** [comment] 2019-03-04 21:38
Closing until there is a response.

**Closed by MarkHerhold** 2019-03-04 21:38 UTC

**Comment by roginneil** [comment] 2019-06-19 03:30
I'm also getting this error on the latest version. I also get this error
node_modules/koa-body/index.d.ts:7:9 - error TS2687: All declarations of 'body' must have identical modifiers.

7         body?: any;

**Comment by roginneil** [comment] 2019-06-19 03:42
I'm also getting the same error on the latest version of the package
node_modules/koa-body/index.d.ts:166:63 - error TS2315: Type 'Middleware' is not generic.

166 declare function koaBody (options?: koaBody.IKoaBodyOptions): Koa.Middleware<{}, {}>;

**Comment by gaoshijun1993** [comment] 2019-07-12 06:15
Came across the same error

**Comment by gaoshijun1993** [comment] 2019-07-26 07:59
Found the reason: the version of @types/koa is too low, upgrading it to the newest solves the problem.
